version: 2.0
jobs: 
  build:
    docker:
     - image: circleci/openjdk:8-jdk
    steps:
     - checkout
     - run:
          name: Build project
          command: gradle jar
     - store_artifacts:
          path: build/libs
          destination: jar
     - run:
          name: Run gradle test
          command: gradle test
     - store_test_results:
          path: build/test-results   
package:
    docker:
     - image: circleci/openjdk:8-jdk
    steps:
     - checkout
     - run:
          name: Build project
          command: gradle jar
     - store_artifacts:
          path: build/libs
          destination: jar
workflows:
  version: 2
  myworkflow:
    jobs: 
     - test
     - package:
          requires:
           - test

