version: 2.0
jobs: 
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
      - run:
	  name: Build project
	  command: gradle jar
      - store_artifacts:
          path: /code/artifact
	  destination: prefix
      - run:
          name: Run gradle test
          command: gradle test
      - store_test_results:
	  path: build/test-results    
